/**
 * AI Whisperers Work Hours Dashboard
 * Static client-side application
 */

// Global state
let workedHoursData = null;
let charts = {
    daily: null,
    repo: null
};

// Initialize on page load
document.addEventListener('DOMContentLoaded', () => {
    initializeTabs();
    loadWorkedHoursData();
});

/**
 * Initialize tab switching
 */
function initializeTabs() {
    const tabButtons = document.querySelectorAll('.tab-button');
    const tabContents = document.querySelectorAll('.tab-content');

    tabButtons.forEach(button => {
        button.addEventListener('click', () => {
            const tabId = button.dataset.tab;

            // Update active states
            tabButtons.forEach(btn => btn.classList.remove('active'));
            tabContents.forEach(content => content.classList.remove('active'));

            button.classList.add('active');
            document.getElementById(tabId).classList.add('active');
        });
    });
}

/**
 * Load worked hours data from JSON file
 */
async function loadWorkedHoursData() {
    try {
        // Fetch the JSON file generated by GitHub Actions
        const response = await fetch('worked_hours.json');

        if (!response.ok) {
            throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }

        workedHoursData = await response.json();

        // Update all UI components
        updateLastUpdated(workedHoursData.generated_at);
        renderContributors(workedHoursData.sessions);
        updateStatistics(workedHoursData.summary);
        renderCharts(workedHoursData);
        renderSessionsTable(workedHoursData.sessions);

    } catch (error) {
        console.error('Failed to load worked hours data:', error);
        showError(error.message);
    }
}

/**
 * Update last updated timestamp
 */
function updateLastUpdated(timestamp) {
    const element = document.getElementById('lastUpdated');
    if (timestamp) {
        const date = new Date(timestamp);
        element.textContent = `Last updated: ${date.toLocaleString()}`;
    } else {
        element.textContent = 'Last updated: Unknown';
    }
}

/**
 * Update statistics cards
 */
function updateStatistics(summary) {
    if (!summary) {
        console.warn('No summary data available');
        return;
    }

    document.getElementById('totalDays').textContent = summary.total_days || 0;
    document.getElementById('totalHours').textContent = (summary.total_hours || 0).toFixed(1) + 'h';
    document.getElementById('totalCommits').textContent = summary.total_commits || 0;
    document.getElementById('avgHoursPerDay').textContent = (summary.avg_hours_per_day || 0).toFixed(1) + 'h';
}

/**
 * Render contributors list
 */
function renderContributors(sessions) {
    const container = document.getElementById('contributorsList');
    if (!container) return;

    if (!sessions || sessions.length === 0) {
        container.innerHTML = '<li class="loading">No contributors found.</li>';
        return;
    }

    // Aggregate hours by author
    const contributorHours = {};
    sessions.forEach(session => {
        const author = session.author;
        if (!contributorHours[author]) {
            contributorHours[author] = 0;
        }
        contributorHours[author] += session.hours;
    });

    // Sort by hours (descending)
    const contributors = Object.entries(contributorHours)
        .map(([author, hours]) => ({ author, hours }))
        .sort((a, b) => b.hours - a.hours);

    // Render contributor items
    container.innerHTML = contributors.map(contributor => `
        <li class="contributor-item">
            <span class="contributor-name">${escapeHtml(contributor.author)}</span>
            <span class="contributor-hours">${contributor.hours.toFixed(1)}h</span>
            <a href="#sessionsTable" class="contributor-link" data-author="${escapeHtml(contributor.author)}">
                View sessions ↓
            </a>
        </li>
    `).join('');

    // Add click handlers to scroll and highlight
    container.querySelectorAll('.contributor-link').forEach(link => {
        link.addEventListener('click', (e) => {
            e.preventDefault();
            const author = link.dataset.author;
            scrollToSessionsTable(author);
        });
    });
}

/**
 * Scroll to sessions table and highlight author's sessions
 */
function scrollToSessionsTable(author) {
    const tableContainer = document.getElementById('sessionsTable');
    if (!tableContainer) return;

    // Scroll to table
    tableContainer.scrollIntoView({ behavior: 'smooth', block: 'start' });

    // Highlight matching rows
    setTimeout(() => {
        const rows = tableContainer.querySelectorAll('.sessions-table tbody tr');
        rows.forEach(row => {
            const authorCell = row.querySelector('.author-name');
            if (authorCell && authorCell.textContent === author) {
                row.style.backgroundColor = 'var(--surface-hover)';
                row.style.borderLeft = '3px solid var(--primary-color)';

                // Remove highlight after 3 seconds
                setTimeout(() => {
                    row.style.backgroundColor = '';
                    row.style.borderLeft = '';
                }, 3000);
            }
        });
    }, 500);
}

/**
 * Render charts
 */
function renderCharts(data) {
    if (!data.daily_hours || !data.repo_hours) {
        console.warn('Missing chart data');
        return;
    }

    renderDailyHoursChart(data.daily_hours);
    renderRepoHoursChart(data.repo_hours);
}

/**
 * Render daily hours line chart
 */
function renderDailyHoursChart(dailyData) {
    const ctx = document.getElementById('dailyHoursChart');
    if (!ctx) return;

    // Destroy existing chart if any
    if (charts.daily) {
        charts.daily.destroy();
    }

    // Prepare data
    const labels = dailyData.map(d => d.date);
    const hours = dailyData.map(d => d.hours);

    charts.daily = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'Hours Worked',
                data: hours,
                borderColor: '#2196F3',
                backgroundColor: 'rgba(33, 150, 243, 0.1)',
                borderWidth: 2,
                tension: 0.4,
                fill: true,
                pointRadius: 4,
                pointHoverRadius: 6
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            plugins: {
                legend: {
                    display: false
                },
                tooltip: {
                    backgroundColor: 'rgba(0, 0, 0, 0.8)',
                    padding: 12,
                    titleColor: '#fff',
                    bodyColor: '#fff',
                    borderColor: '#2196F3',
                    borderWidth: 1
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                    ticks: {
                        color: '#8b949e',
                        callback: function(value) {
                            return value + 'h';
                        }
                    },
                    grid: {
                        color: '#30363d'
                    }
                },
                x: {
                    ticks: {
                        color: '#8b949e'
                    },
                    grid: {
                        color: '#30363d'
                    }
                }
            }
        }
    });
}

/**
 * Render repository hours bar chart
 */
function renderRepoHoursChart(repoData) {
    const ctx = document.getElementById('repoHoursChart');
    if (!ctx) return;

    // Destroy existing chart if any
    if (charts.repo) {
        charts.repo.destroy();
    }

    // Prepare data (sort by hours, take top 10)
    const sortedRepos = [...repoData]
        .sort((a, b) => b.hours - a.hours)
        .slice(0, 10);

    const labels = sortedRepos.map(r => r.repo);
    const hours = sortedRepos.map(r => r.hours);

    charts.repo = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Hours',
                data: hours,
                backgroundColor: '#4CAF50',
                borderColor: '#4CAF50',
                borderWidth: 0,
                borderRadius: 4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: true,
            indexAxis: 'y',
            plugins: {
                legend: {
                    display: false
                },
                tooltip: {
                    backgroundColor: 'rgba(0, 0, 0, 0.8)',
                    padding: 12,
                    titleColor: '#fff',
                    bodyColor: '#fff',
                    borderColor: '#4CAF50',
                    borderWidth: 1
                }
            },
            scales: {
                x: {
                    beginAtZero: true,
                    ticks: {
                        color: '#8b949e',
                        callback: function(value) {
                            return value + 'h';
                        }
                    },
                    grid: {
                        color: '#30363d'
                    }
                },
                y: {
                    ticks: {
                        color: '#8b949e'
                    },
                    grid: {
                        display: false
                    }
                }
            }
        }
    });
}

/**
 * Render sessions table
 */
function renderSessionsTable(sessions) {
    const container = document.getElementById('sessionsTable');
    if (!container) return;

    if (!sessions || sessions.length === 0) {
        container.innerHTML = '<p class="loading">No work sessions found.</p>';
        return;
    }

    // Sort by start time (most recent first)
    const sortedSessions = [...sessions]
        .sort((a, b) => new Date(b.start) - new Date(a.start))
        .slice(0, 50); // Show last 50 sessions

    const table = document.createElement('table');
    table.className = 'sessions-table';

    // Table header
    table.innerHTML = `
        <thead>
            <tr>
                <th>Date</th>
                <th>Author</th>
                <th>Repository</th>
                <th>Time Range</th>
                <th>Commits</th>
                <th>Hours</th>
            </tr>
        </thead>
        <tbody>
            ${sortedSessions.map(session => `
                <tr>
                    <td>${formatDate(session.start)}</td>
                    <td><span class="author-name">${escapeHtml(session.author)}</span></td>
                    <td><span class="repo-badge">${escapeHtml(session.repo)}</span></td>
                    <td>${formatTimeRange(session.start, session.end)}</td>
                    <td><span class="commit-count">${session.commit_count} commits</span></td>
                    <td><span class="hours-badge">${session.hours.toFixed(2)}h</span></td>
                </tr>
            `).join('')}
        </tbody>
    `;

    container.innerHTML = '';
    container.appendChild(table);
}

/**
 * Format date for display
 */
function formatDate(dateString) {
    const date = new Date(dateString);
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);

    if (date.toDateString() === today.toDateString()) {
        return 'Today';
    } else if (date.toDateString() === yesterday.toDateString()) {
        return 'Yesterday';
    } else {
        return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    }
}

/**
 * Format time range
 */
function formatTimeRange(start, end) {
    const startTime = new Date(start).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    const endTime = new Date(end).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    return `${startTime} - ${endTime}`;
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHtml(text) {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
}

/**
 * Show error message
 */
function showError(message) {
    const workedHoursTab = document.getElementById('worked-hours');
    if (!workedHoursTab) return;

    workedHoursTab.innerHTML = `
        <div class="error">
            <h2>⚠️ Failed to Load Data</h2>
            <p>${escapeHtml(message)}</p>
            <p style="margin-top: 10px; font-size: 0.9rem;">
                The <code>worked_hours.json</code> file may not exist yet.
                Please wait for the next GitHub Actions run to generate the data.
            </p>
        </div>
    `;
}
